#pragma once
#pragma execution_character_set("utf-8")

// 样式表文件
#include <QString>

static const QString WidgetStyleSheet =
    "font: 9pt 幼圆;"
    "QWidget {background-color: #D1E7DD;}"
    "QWidget::title{ color: #135E46;}";

static const QString MainWindowStyleSheet =
    "font: 9pt 幼圆;"
    "QMainWindow {background-color: #D1E7DD;}"
    "QMainWindow::title {color: #135E46;}";

static const QString TableWidgetStyleSheet =
    "QTableWidget {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 3px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "} "
    "QTableWidget:item{"
    "background-color: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "} "
    "QTableWidget:hover{"
    "border: 1px solid #00BB9E;"
    "} "
    "QTableWidget:selected{"
    "border: 1px solid #00BB9E;"
    "} "
    "QTableWidget:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "} "
    "QTableWidget QHeaderView::section {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "min-height: 20px;"
    "} "
    "QTableWidget QHeaderView::section:hover {"
    "background-color: #00BB9E;"
    "} "
    "QTableWidget QHeaderView::section:selected {"
    "background-color: #00BB9E;"
    "} "
    "QTableWidget QAbstractItemView {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "selection-background-color: #00BB9E;"
    "} "
    "QTableWidget QAbstractItemView::item {"
    "height: 20px;"
    "} "
    "QTableWidget::item:selected {"
    "color: cyan;"
    "}";

// Implementing in MainWindow
static const QString MenuBarStyleSheet;

static const QString ToolBarStyleSheet =
    "QToolBar {"
    "border: none;"
    "padding: 1px;"
    "}"
    "QToolBar QToolButton : hover{"
    "background - color: #E6F0E6; /* hover color */"
    "border: 2px solid #00BB9E;"
    "}"
    "QToolBar QToolButton : pressed{"
    "background - color: #969696;"
    "border: 2px solid #00BB9E;"
    "}";

static const QString ComboBoxStyleSheet =
    "QComboBox {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 3px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "} "
    "QComboBox:item{"
    "background-color: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "} "
    "QComboBox:hover{"
    "border: 1px solid #00BB9E;"
    "} "
    "QComboBox:selected{"
    "border: 1px solid #00BB9E;"
    "} "
    "QComboBox:editable{"
    "background-color: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "} "
    "QComboBox:editable:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "} "
    "QComboBox QAbstractItemView {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "selection-background-color: #00BB9E;"
    "} "
    "QComboBox QAbstractItemView::item {"
    "height: 20px;"
    "} "
    "QComboBox::drop-down {"
    "width: 20px;"
    "height: 20px;"
    "subcontrol-position: center right;"
    "right: 2px;"
    "border: 0;"
    "background-color: transparent;"
    "} "
    "QComboBox::down-arrow {"
    "width: 20px;"
    "height: 20px;"
    "border-image: url(:/icon/triangle_down_969696.png);"
    "} "
    "QComboBox::down-arrow:hover {"
    "border-image: url(:/icon/triangle_down_00BB9E.png);"
    "} "
    "QComboBox::disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "} "
    "QComboBox::down-arrow:disabled {"
    "border-image: url(:/icon/triangle_down_404244.png);"
    "}";

static const QString PushButtonStyleSheet =
    "QPushButton {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 3px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "border-radius: 20px;"
    "}"
    "QPushButton:hover{"
    "border: 1px solid #00BB9E;"
    "}"
    "QPushButton:pressed{"
    "border: 1px solid #00BB9E;"
    "}"
    "QPushButton:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "}";

static const QString DialogButtonBoxStyleSheet =
    "QDialogButtonBox QPushButton {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 5px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "width: 60px;"
    "height: 20px;"
    "text-align: center;"
    "}"
    "QDialogButtonBox QPushButton:hover{"
    "border: 1px solid #00BB9E;"
    "}"
    "QDialogButtonBox QPushButton:pressed{"
    "border: 1px solid #00BB9E;"
    "}"
    "QDialogButtonBox QPushButton:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "}"
    "QDialogButtonBox {"
    "button-layout: 0;"
    "}";

static const QString LineEditStyleSheet =
    "QLineEdit {"
    "border: 1px solid gray;"
    "border-radius: 5px;"
    "padding: 0 8px;"
    "background: white;"
    "selection-background-color: darkgray;"
    "}";

static const QString SpinBoxStyleSheet =
    "QSpinBox {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 3px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "border-radius: 20px;"
    "}"
    "QSpinBox:hover{"
    "border: 1px solid #00BB9E;"
    "}"
    "QSpinBox:pressed{"
    "border: 1px solid #00BB9E;"
    "}"
    "QSpinBox:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "}";

static const QString DoubleSpinBoxStyleSheet =
    "QDoubleSpinBox {"
    "border: 1px solid #969696;"
    "background: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F2F3F4 , stop:1 #E7E9EB);"
    "border-radius: 3px;"
    "padding: 1px 18px 1px 3px;"
    "min-height: 20px;"
    "border-radius: 20px;"
    "}"
    "QDoubleSpinBox:hover{"
    "border: 1px solid #00BB9E;"
    "}"
    "QDoubleSpinBox:pressed{"
    "border: 1px solid #00BB9E;"
    "}"
    "QDoubleSpinBox:disabled{"
    "color: #DCE1E6;"
    "background-color: #F5F5F5;"
    "border: 1px solid #969696;"
    "}";